### ISSUE TITLE
Not able to scroll

### ISSUE THREAD

**Issue by sauravexodus** [RStankov/RDSActionLabel#3]
This happens when you have **RDSActionLabel** in a scrollview and it has multiple lines, then the **Scrollview** refuses to capture gestures for scrolling.

**Comment by RSBartesania** [comment]
Same problem.... Is there any way to solve it?

Thanks

**Comment by RSBartesania** [comment]
@sauravexodus @RStankov 
I just edited this line within RDSActionLabel.swift class

public override func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
       ////return textAtLocation(location: gestureRecognizer.location(in: self)) != nil 
        return true 
    }

**Comment by RStankov** [comment]
@RSBartesania if this fixes it, can you open PR?

**Comment by sauravexodus** [comment]
I also did the same workaround earlier :) @RSBartesania
