### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by robertocorrales** [RStankov/RDSActionLabel#5]
Hi, I've been using this library for a few years and I see that now, with iOS15 and Xcode13 it doesn't work any more the actions (match)

Thanks

**Comment by RStankov** [comment]
I don't support the library any more.

**Comment by robertocorrales** [comment]
Oh no! Well... thanks anyway.
Do you know any other library similar to yours?

**Comment by RStankov** [comment]
@robertocorrales I don't know. I haven't done much iOS development in the last 3-4 years.
